# Generated by Django 6.1.1 on 2026-09-25 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loads', '0001_initial'),
        ('trips', '0003_triplocationupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('report_type', models.CharField(choices=[('cargo_damaged', 'Cargo Damaged'), ('cargo_missing', 'Cargo Missing'), ('wrong_weight_quantity', 'Wrong Weight/Quantity'), ('truck_capacity_issue', 'Truck Capacity Issue'), ('driver_misbehavior', 'Driver Misbehavior'), ('truck_condition_problem', 'Truck Condition Problem'), ('delivery_delay', 'Delivery Delay'), ('delivery_not_completed', 'Delivery Not Completed'), ('owner_misbehavior', 'Owner Misbehavior'), ('payment_issue', 'Payment Issue'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('expected_information', models.TextField(blank=True, null=True)),
                ('actual_information', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('waiting_for_customer', 'Waiting for Customer'), ('waiting_for_owner', 'Waiting for Owner'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='loads.load')),
                ('reported_against', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_against', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='trips.trip')),
            ],
        ),
    ]
