# Generated by Django 6.1.1 on 2026-09-30 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0001_initial'),
        ('reports', '0001_initial'),
        ('trips', '0003_triplocationupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='loads.load'),
        ),
        migrations.AlterField(
            model_name='report',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='trips.trip'),
        ),
    ]
