# Generated by Django 6.1.1 on 2026-09-25 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0003_triplocationupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_type', models.CharField(choices=[('delivery_receipt', 'Delivery Receipt / POD'), ('customer_signature', 'Customer Signature'), ('photo', 'Photo'), ('document', 'Document')], max_length=30)),
                ('file', models.FileField(upload_to='delivery_proofs/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_proofs', to='trips.trip')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_delivery_proofs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
