# Generated by Django 6.1.1 on 2026-09-24 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/')),
                ('mobile_number', models.CharField(max_length=20)),
                ('driving_licence', models.FileField(blank=True, null=True, upload_to='driver_documents/')),
                ('licence_number', models.CharField(max_length=100, unique=True)),
                ('licence_expiry', models.DateField()),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('address', models.TextField()),
                ('emergency_contact', models.CharField(max_length=20)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'truck_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
