# Generated by Django 6.1.1 on 2026-09-25 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disputes', '0001_initial'),
        ('reports', '0001_initial'),
        ('trips', '0003_triplocationupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_already_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_settlement_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('settlement_type', models.CharField(choices=[('customer_compensation', 'Customer Compensation'), ('additional_owner_payment', 'Additional Owner Payment'), ('fare_reduction', 'Fare Reduction'), ('cancellation_compensation', 'Cancellation Compensation'), ('damage_compensation', 'Damage Compensation'), ('payment_adjustment', 'Payment Adjustment'), ('other', 'Other')], max_length=50)),
                ('reason', models.TextField()),
                ('evidence', models.TextField(blank=True, default='')),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('under_review', 'Under Review'), ('settlement_proposed', 'Settlement Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('settled', 'Settled'), ('cancelled', 'Cancelled')], default='pending_review', max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('dispute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='disputes.dispute')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_to_pay', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_to_receive', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='reports.report')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_settlements', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='trips.trip')),
            ],
        ),
    ]
