# Generated by Django 6.1.1 on 2026-09-25 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0003_triplocationupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('notification_type', models.CharField(choices=[('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('driver_assigned', 'Driver Assigned'), ('trip_started', 'Trip Started'), ('trip_status_changed', 'Trip Status Changed'), ('payment_received', 'Payment Received'), ('payment_due', 'Payment Due'), ('payment_overdue', 'Payment Overdue'), ('delivery_completed', 'Delivery Completed'), ('report_created', 'Report Created'), ('report_updated', 'Report Updated'), ('settlement_completed', 'Settlement Completed'), ('document_expiring', 'Document Expiring'), ('payment_reminder', 'Payment Reminder'), ('settlement_update', 'Settlement Update'), ('report_update', 'Report Update'), ('dispute_update', 'Dispute Update'), ('document_verification', 'Document Verification'), ('trip_issue', 'Trip Issue'), ('cancellation', 'Cancellation'), ('important_announcement', 'Important Announcement'), ('account_warning', 'Account Warning'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='trips.trip')),
            ],
        ),
    ]
