# Generated by Django 6.1.1 on 2026-09-24 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('loads', '0001_initial'),
        ('trucks', '0002_alter_truck_base_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('start_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('current_location', models.CharField(max_length=255)),
                ('current_status', models.CharField(choices=[('trip_confirmed', 'Trip Confirmed'), ('driver_assigned', 'Driver Assigned'), ('driver_reached_pickup', 'Driver Reached Pickup'), ('loading_completed', 'Loading Completed'), ('journey_started', 'Journey Started'), ('in_transit', 'In Transit'), ('near_destination', 'Near Destination'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('trip_completed', 'Trip Completed'), ('cancelled', 'Cancelled'), ('issue_reported', 'Issue Reported'), ('under_review', 'Under Review')], default='trip_confirmed', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trip', to='bookings.booking')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='loads.load')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='trucks.truck')),
            ],
        ),
    ]
