# Generated by Django 6.1.1 on 2026-09-25 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripLocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trip_confirmed', 'Trip Confirmed'), ('driver_assigned', 'Driver Assigned'), ('driver_reached_pickup', 'Driver Reached Pickup'), ('loading_completed', 'Loading Completed'), ('journey_started', 'Journey Started'), ('in_transit', 'In Transit'), ('near_destination', 'Near Destination'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('trip_completed', 'Trip Completed'), ('cancelled', 'Cancelled'), ('issue_reported', 'Issue Reported'), ('under_review', 'Under Review')], max_length=30)),
                ('location', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trip_updates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to='trips.trip')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_location_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
