# Generated by Django 6.1.1 on 2026-09-25 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('trips', '0003_triplocationupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('waiting_for_customer', 'Waiting for Customer'), ('waiting_for_owner', 'Waiting for Owner'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='open', max_length=30)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_created', to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='reports.report')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='trips.trip')),
            ],
        ),
    ]
