# Generated by Django 6.1.1 on 2026-09-30 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
        ('reports', '0002_alter_report_load_alter_report_trip'),
        ('trips', '0003_triplocationupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='reports.report'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='trips.trip'),
        ),
    ]
