# Generated by Django 6.1.1 on 2026-09-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_dispute_reason_alter_dispute_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='evidence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dispute',
            name='respondent_evidence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dispute',
            name='respondent_response',
            field=models.TextField(blank=True, default=''),
        ),
    ]
